name=ChipNorm_DHT11
version=1.0.0
author=Chipnorm
maintainer=Chipnorm
sentence=Library for the DHT11 Sensor. Read out easily the temperature and moisture.
paragraph=Used to measure temperature and moisture.
category=Sensors
url=https://github.com/chipnorm/ChipNorm_DHT11.git
architectures=*
